# Generated by Django 3.2.6 on 2021-08-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='avatar',
            new_name='article',
        ),
    ]
